Repository algebraicdb/algebraicdb, pull requests merged in 2020-02, with the labels that each got.

#11 Implement check_expr for the type checker
  Cargo.toml
  src/ast.rs
  src/global/manager.rs
  src/global/tests.rs
  src/global/types.rs
  src/grammar.lalrpop
  src/grammar.rs
  src/main.rs
  src/pattern.rs
  src/pre_typechecker.rs
  src/primitive.rs
  src/table.rs
  src/typechecker.rs
  src/types.rs
Labels: enhancement, question

#16 Add Create Table to grammar and typechecker
  src/ast.rs
  src/grammar.lalrpop
  src/pre_typechecker.rs
  src/typechecker.rs
Labels: grammar

#15 Implement typechecker for INSERT
  src/typechecker.rs
Labels: pls_merge

#18 Implement a full slice of database
  src/ast.rs
  src/executor.rs
  src/global/manager.rs
  src/global/tests.rs
  src/global/types.rs
  src/grammar.lalrpop
  src/main.rs
  src/pre_typechecker.rs
  src/table.rs
  src/typechecker.rs
  src/types.rs
Labels: enhancement

#21 Implement select in executor
  src/executor.rs
  src/grammar.lalrpop
  src/pattern.rs
  src/table.rs
  src/typechecker.rs
Labels: enhancement

#23 Basic implementation of drop table in grammar, needs more work
  src/ast.rs
  src/global/types.rs
  src/grammar.lalrpop
  src/pre_typechecker.rs
  src/typechecker.rs
Labels: enhancement, grammar

#22 Added function to get base type id
  src/table.rs
  src/typechecker.rs
  src/types.rs
Labels: pls_merge, refactor

#24 Executor gets a Writer instead of returning a string
  src/api/tcp_api.rs
  src/executor.rs
  src/main.rs
Labels: refactor

#26 Pretty print SELECT:s
  src/api/tcp_api.rs
  src/executor.rs
  src/pattern.rs
  src/table/cell.rs
  src/table/iter.rs
  src/table/mod.rs
  src/table/pattern_iter.rs
  src/table/row.rs
  src/table/schema.rs
Labels: enhancement, pls_merge, refactor

#28 Add support for inserting multiple values at once
  src/ast.rs
  src/executor.rs
  src/grammar.lalrpop
  src/typechecker.rs
Labels: enhancement, grammar

#33 Add async await everywhere
  src/api/tcp_api.rs
  src/executor.rs
  src/global/api.rs
  src/global/manager.rs
  src/global/tests.rs
  src/global/types.rs
  src/main.rs
  src/typechecker.rs
Labels: enhancement, refactor

#38 yeet global
  Cargo.lock
  Cargo.toml
  docker-compose.yml
  src/api/tcp_api.rs
  src/ast.rs
  src/executor.rs
  src/global/api.rs
  src/global/manager.rs
  src/global/mod.rs
  src/local/dbms_state.rs
  src/local/mod.rs
  src/local/tests.rs
  src/local/types.rs
  src/main.rs
  src/pre_typechecker.rs
  src/psqlwrapper/mapping.rs
  src/psqlwrapper/mod.rs
  src/psqlwrapper/translator/insert.rs
  src/psqlwrapper/translator/mod.rs
  src/psqlwrapper/translator/translator.rs
  src/psqlwrapper/wrapper.rs
  src/table/mod.rs
  src/typechecker.rs
Labels: pls_merge

#41 Only print rows added on INSERT INTO
  src/executor.rs
Labels: enhancement, pls_merge

#40 Properly close threads along with socket
  src/api/tcp_api.rs
Labels: bug, pls_merge

#47 Refactor Conga
  Cargo.lock
  Cargo.toml
  src/api/tcp_api.rs
Labels: pls_merge, refactor

#50 Add example queries and their expected output
  test_queries/1/input
  test_queries/1/output
  test_queries/2/input
  test_queries/2/output
  test_queries/README.md
Labels: tests

#51 Refactor database as library & add integration test
  Cargo.lock
  Cargo.toml
  src/api/custom.rs
  src/api/mod.rs
  src/api/tcp_api.rs
  src/client.rs
  src/executor/dbms.rs
  src/executor/mod.rs
  src/executor/wrapper.rs
  src/lib.rs
  src/local/mod.rs
  src/main.rs
  src/psqlwrapper/wrapper.rs
  test_queries/1/output
  test_queries/2/output
  test_queries/3/input
  test_queries/3/output
  test_queries/4/input
  test_queries/4/output
  tests/test_example_queries.rs
Labels: enhancement, refactor, tests

#54 Implement duck-typing
  src/grammar.lalrpop
  src/pattern.rs
  src/typechecker.rs
  src/types.rs
  test_queries/5/input
  test_queries/5/output
Labels: enhancement, grammar, refactor, typechecker
